### ISSUE TITLE
MSR-1_BLE ESPHome install error - light.neopixelbus

### ISSUE THREAD

**Issue by stumain** [ApolloAutomation/MSR-1#52]
Trying to use the BLE enabled edition of the firmware for an MSR-1 but receive an error for light.neopixelbus in core.yaml.  Documentation on https://esphome.io/components/light/neopixelbus.html suggests this feature is not availble when using ESP-IDF.

Tried removing the use of the ESP-IDF and the firmware compile and install works.  Will wait and see how stable the MSR-1 using this.

Could be documentation update to remove the use of ESP-IDF or removal of neopixel functions if ESP-IDF is still required for another reason?

BTW, Awesome little sensors!!

**Comment by neilmartin83** [comment]
If you are using ESP-IDF add this to your config in the ESPHome Builder to get the light working. esp32_rmt_led_strip is a replacement for neopixelbus.

```
light:
    platform: esp32_rmt_led_strip
    id: rgb_light
    name: RGB Light
    pin: GPIO3
    num_leds: 1
    rmt_channel: 0
    rgb_order: GRB
    chipset: ws2812
```
